services:
  guess-number-tdd:
    build: .
    container_name: ipc26-guess-number
    command: sh -c "composer install --no-interaction && tail -f /dev/null"
    working_dir: /srv/workshop-ipc26-berlin/tdd/guess-random-number
    volumes:
      - .:/srv/workshop-ipc26-berlin/tdd/guess-random-number:delegated
    environment:
      XDEBUG_MODE: debug
      XDEBUG_SESSION: PHPSTORM
